Comment out gl4es related steps in workflow
Comment out steps related to gl4es fetching, caching, building, and installation.

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -24,46 +24,46 @@ jobs:
       with:
         java-version: 1.8
 
-    - name: Get gl4es latest commit hash
-      id: gl4es-sha
-      run: echo "::set-output name=sha::$(echo $(git ls-remote https://github.com/PojavLauncherTeam/gl4es refs/heads/master | grep -io '^\S*' && git ls-remote https://github.com/ptitSeb/gl4es refs/heads/master | grep -io '^\S*'))"
-      shell: bash
+ #   - name: Get gl4es latest commit hash
+  #    id: gl4es-sha
+ #     run: echo "::set-output name=sha::$(echo $(git ls-remote https://github.com/PojavLauncherTeam/gl4es refs/heads/master | grep -io '^\S*' && git ls-remote https://github.com/ptitSeb/gl4es refs/heads/master | grep -io '^\S*'))"
+ #     shell: bash
       
-    - name: Cache gl4es
-      uses: actions/cache@v4
-      id: gl4es-cache
-      with:
-        path: gl4es/libs
-        key: gl4es-android-shared-nodbg-test1-1-${{ steps.gl4es-sha.outputs.sha }}
+#    - name: Cache gl4es
+#      uses: actions/cache@v4
+ #     id: gl4es-cache
+ #     with:
+ #       path: gl4es/libs
+ #       key: gl4es-android-shared-nodbg-test1-1-${{ steps.gl4es-sha.outputs.sha }}
 
-    - name: Get gl4es
-      if: steps.gl4es-cache.outputs.cache-hit != 'true'
-      uses: actions/checkout@v4
-      with:
-        repository: 'ptitSeb/gl4es'
-        path: 'gl4es'
+ #   - name: Get gl4es
+#      if: steps.gl4es-cache.outputs.cache-hit != 'true'
+ #     uses: actions/checkout@v4
+   #   with:
+   #     repository: 'ptitSeb/gl4es'
+   #     path: 'gl4es'
 
-    - name: Build gl4es
-      if: steps.gl4es-cache.outputs.cache-hit != 'true'
-      continue-on-error: true
-      run: |
-        cd gl4es
-        git config --global user.email "PojavLauncherTeam@users.noreply.github.com"
-        git config --global user.name "PojavLauncherTeam"
-        git remote add upstream https://github.com/PojavLauncherTeam/gl4es
-        git fetch upstream
-        git checkout master
-        git merge --allow-unrelated-histories upstream/master || echo "Merge exit code $?"
-        $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk
+  #  - name: Build gl4es
+     # if: steps.gl4es-cache.outputs.cache-hit != 'true'
+    #  continue-on-error: true
+   #   run: |
+ #       cd gl4es
+       # git config --global user.email "PojavLauncherTeam@users.noreply.github.com"
+     #   git config --global user.name "PojavLauncherTeam"
+    #    git remote add upstream https://github.com/PojavLauncherTeam/gl4es
+  #      git fetch upstream
+    #    git checkout master
+    #    git merge --allow-unrelated-histories upstream/master || echo "Merge exit code $?"
+   #     $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk
     
-    - name: Install gl4es
-      if: steps.gl4es-cache.outputs.cache-hit != 'true'
-      run: |
-        cp -R gl4es/libs/* app_pojavlauncher/src/main/jniLibs/
-        mv gl4es ..
-        git add .
-        git commit -am "CI: Update gl4es"
-        git push
+  #  - name: Install gl4es
+  #    if: steps.gl4es-cache.outputs.cache-hit != 'true'
+  #    run: |
+    #    cp -R gl4es/libs/* app_pojavlauncher/src/main/jniLibs/
+    #    mv gl4es ..
+   #     git add .
+   #     git commit -am "CI: Update gl4es"
+      #  git push
     
     - name: Get JRE8
       uses: dawidd6/action-download-artifact@v4
